### ISSUE TITLE
ESPHome unknown entities

### ISSUE THREAD

**Issue by PZotya** [lufton/esphome-inv-8851#29]
Hi!

Buiding az ESPHome all entities of my device has unknown state.
![ha-powmr](https://github.com/user-attachments/assets/10596f65-0cf3-4fc5-b726-0c171c3b6d24)

My hardware setup:
The SBC is an ESP 8266 Wemos D1 mini, the power source is an 5V buck converter feeded form the inverter's pin 4 and 8.
The data cables are connected to the Wemos RX and DX pins, through a max232 board, which has a a power source the 3.3V of D1 mini.
The esphome version is 2024.9.2, Firmware: 2024.9.2 (Oct 19 2024, 12:05:21)

The inverter is a POW-HVM6.5K-48V.

**Comment by PZotya** [comment]
This is my yaml config:
```
substitutions:
  inverter_maximum_power: "6500"
  version: "2"
  name: powmr
  friendly_name: "PowMr Inverter"
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO3

esp8266:
  board: d1_mini

packages:
  core: !include packages/core-local.yaml
  inverter: !include packages/inverter.yaml
  grid: !include packages/grid.yaml
  temperature: !include packages/temperature.yaml
  battery: !include packages/battery.yaml
  battery-48v: !include packages/battery-48v.yaml
  # pv: !include packages/pv.yaml
  # parallel: !include packages/parallel.yaml
  # bms-48v: !include packages/bms-48v.yaml

wifi:
  ssid: "yyyyyyyy"
  password: "xxxxxx"

  ap:
    ssid: "Powmr Fallback Hotspot"
    password: "RDmLwgXZMgYm"

api:


ota:
  - platform: esphome
    password: "xxxxxxxx"
logger:
  baud_rate: 0 
```
